//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunSales.NHibernate.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunSales.NHibernate.Core.Resources.Core", typeof(Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un produs cu acelasi lot pe aviz!.
        /// </summary>
        internal static string AvizDetaliuDublat {
            get {
                return ResourceManager.GetString("AvizDetaliuDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un aviz cu aceeasi serie si numar:{0}.
        /// </summary>
        internal static string AvizDublat {
            get {
                return ResourceManager.GetString("AvizDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avizul este deja validat!.
        /// </summary>
        internal static string AvizValidat {
            get {
                return ResourceManager.GetString("AvizValidat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o campanie cu aceeasi denumire.
        /// </summary>
        internal static string CampanieDublata {
            get {
                return ResourceManager.GetString("CampanieDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o grupa client cu aceeasi denumire.
        /// </summary>
        internal static string CategorieClientDublata {
            get {
                return ResourceManager.GetString("CategorieClientDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un punct de lucru cu aceasta adresa!.
        /// </summary>
        internal static string ClientPunctLucruAdresaDublat {
            get {
                return ResourceManager.GetString("ClientPunctLucruAdresaDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un client cu acelasi cod extern!.
        /// </summary>
        internal static string ClientPunctLucruCodExternDublat {
            get {
                return ResourceManager.GetString("ClientPunctLucruCodExternDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un client cu acelasi cod fiscal!.
        /// </summary>
        internal static string ClientPunctLucruCodFiscalDublat {
            get {
                return ResourceManager.GetString("ClientPunctLucruCodFiscalDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un client cu acelasi cod intern!.
        /// </summary>
        internal static string ClientPunctLucruCodInternDublat {
            get {
                return ResourceManager.GetString("ClientPunctLucruCodInternDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientul mai este setat pe alta filiala!.
        /// </summary>
        internal static string ClientSetatFiliala {
            get {
                return ResourceManager.GetString("ClientSetatFiliala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod set inexistent, importati produsele.
        /// </summary>
        internal static string CodSetInexistent {
            get {
                return ResourceManager.GetString("CodSetInexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o comanda cu acelasi: client, data, agent, valoare!.
        /// </summary>
        internal static string ComandaDublata {
            get {
                return ResourceManager.GetString("ComandaDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai este o firma cu acelasi CUI!.
        /// </summary>
        internal static string CUIDublat {
            get {
                return ResourceManager.GetString("CUIDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de inceput trebuie sa fie 1 a lunii!.
        /// </summary>
        internal static string DataInceput {
            get {
                return ResourceManager.GetString("DataInceput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de sfarsit trebuie sa fie la {0} a lunii!.
        /// </summary>
        internal static string DataSfarsit {
            get {
                return ResourceManager.GetString("DataSfarsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitatea de masura a valabilitatii depaseste 10 caractere!.
        /// </summary>
        internal static string DenumireUMValabilitatePreaMare {
            get {
                return ResourceManager.GetString("DenumireUMValabilitatePreaMare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un detaliu de grupa preturi client cu acelasi produs!.
        /// </summary>
        internal static string DiscountDublat {
            get {
                return ResourceManager.GetString("DiscountDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o divizie cu aceasi denumire!.
        /// </summary>
        internal static string DivizieDublata {
            get {
                return ResourceManager.GetString("DivizieDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un document plata cu aceeasi serie si numar!.
        /// </summary>
        internal static string DocumentPlataDublat {
            get {
                return ResourceManager.GetString("DocumentPlataDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti acces!.
        /// </summary>
        internal static string EroareAcces {
            get {
                return ResourceManager.GetString("EroareAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti drepturi in aceasta sectiune!.
        /// </summary>
        internal static string EroareAccesSectiune {
            get {
                return ResourceManager.GetString("EroareAccesSectiune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti acces in aceasta zona!.
        /// </summary>
        internal static string EroareAccesZona {
            get {
                return ResourceManager.GetString("EroareAccesZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti adauga pozitia, avizul a este anulat!.
        /// </summary>
        internal static string EroareAdaugarePozitieAvizAnulat {
            get {
                return ResourceManager.GetString("EroareAdaugarePozitieAvizAnulat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti adauga pozitia, avizul a fost preluat pe telefon!.
        /// </summary>
        internal static string EroareAdaugarePozitieAvizPreluat {
            get {
                return ResourceManager.GetString("EroareAdaugarePozitieAvizPreluat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti adauga pozitia, avizul este validat!.
        /// </summary>
        internal static string EroareAdaugarePozitieAvizValidat {
            get {
                return ResourceManager.GetString("EroareAdaugarePozitieAvizValidat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate anula avizul dupa validare!.
        /// </summary>
        internal static string EroareAnulareAviz {
            get {
                return ResourceManager.GetString("EroareAnulareAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} clienti pe aceasta campanie! Va rugam realocati clientii pe alta campanie sau scoateti campania de pe clienti inainte de anulare!.
        /// </summary>
        internal static string EroareAnulareCampanie {
            get {
                return ResourceManager.GetString("EroareAnulareCampanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} clienti pe aceasta categorie! Va rugam realocati clientii pe alta categorie inainte de anulare!.
        /// </summary>
        internal static string EroareAnulareCategorieClient {
            get {
                return ResourceManager.GetString("EroareAnulareCategorieClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta divizie! Va rugam realocati produsele pe alta divizie inainte de anulare.
        /// </summary>
        internal static string EroareAnulareDivizie {
            get {
                return ResourceManager.GetString("EroareAnulareDivizie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta grupa! Va rugam realocati produsele pe alta grupa inainte de anulare.
        /// </summary>
        internal static string EroareAnulareGrupa {
            get {
                return ResourceManager.GetString("EroareAnulareGrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} clienti pe aceasta grupa de discounturi! Va rugam realocati clientii pe alta grupa de discounturi sau stergeti grupa de discounturi de pe client inainte de anulare..
        /// </summary>
        internal static string EroareAnulareGrupaDiscounturiClienti {
            get {
                return ResourceManager.GetString("EroareAnulareGrupaDiscounturiClienti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta grupa de discounturi! Va rugam realocati produsele pe alta grupa de discounturi sau stergeti grupa de discounturi de pe produs inainte de anulare..
        /// </summary>
        internal static string EroareAnulareGrupaDiscounturiProduse {
            get {
                return ResourceManager.GetString("EroareAnulareGrupaDiscounturiProduse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} clienti pe aceasta grupa de pret! Va rugam realocati clientii pe alta grupa de pret sau stergeti grupa de pret de pe client inainte de anulare.
        /// </summary>
        internal static string EroareAnulareGrupaPreturiClient {
            get {
                return ResourceManager.GetString("EroareAnulareGrupaPreturiClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti face nici o operatie, avizul este anulat!.
        /// </summary>
        internal static string EroareAvizAnulat {
            get {
                return ResourceManager.GetString("EroareAvizAnulat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientul nu are Id sau cod extern!.
        /// </summary>
        internal static string EroareClientID {
            get {
                return ResourceManager.GetString("EroareClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNP incorect!.
        /// </summary>
        internal static string EroareCNP {
            get {
                return ResourceManager.GetString("EroareCNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod fiscal incorect!.
        /// </summary>
        internal static string EroareCodFiscal {
            get {
                return ResourceManager.GetString("EroareCodFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod licenta gresit!.
        /// </summary>
        internal static string EroareCodLicenta {
            get {
                return ResourceManager.GetString("EroareCodLicenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate confirma de primire pe telefon, avizul este in editare!.
        /// </summary>
        internal static string EroareConfirmareAviz {
            get {
                return ResourceManager.GetString("EroareConfirmareAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un CUI valid!.
        /// </summary>
        internal static string EroareCUI {
            get {
                return ResourceManager.GetString("EroareCUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti anula o divizie implicita!.
        /// </summary>
        internal static string EroareDivizieImplicita {
            get {
                return ResourceManager.GetString("EroareDivizieImplicita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti drepturi!.
        /// </summary>
        internal static string EroareDrepturi {
            get {
                return ResourceManager.GetString("EroareDrepturi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti drepturi de administrare!.
        /// </summary>
        internal static string EroareDrepturiAdministrare {
            get {
                return ResourceManager.GetString("EroareDrepturiAdministrare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti drepturi de agent!.
        /// </summary>
        internal static string EroareDrepturiAgent {
            get {
                return ResourceManager.GetString("EroareDrepturiAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti drepturi sa intrati aici!.
        /// </summary>
        internal static string EroareDrepturiAviz {
            get {
                return ResourceManager.GetString("EroareDrepturiAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti drepturi de manager!.
        /// </summary>
        internal static string EroareDrepturiManager {
            get {
                return ResourceManager.GetString("EroareDrepturiManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folositi litere si cifre in nume de utilizator!.
        /// </summary>
        internal static string EroareFormatareNumeUtilizator {
            get {
                return ResourceManager.GetString("EroareFormatareNumeUtilizator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folositi litere si cifre in parola!.
        /// </summary>
        internal static string EroareFormatareParola {
            get {
                return ResourceManager.GetString("EroareFormatareParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format incorect la cod fiscal!.
        /// </summary>
        internal static string EroareFormatCUI {
            get {
                return ResourceManager.GetString("EroareFormatCUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID inexistent.
        /// </summary>
        internal static string EroareID {
            get {
                return ResourceManager.GetString("EroareID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limita minima la aviz e mai mare decat limita maxima!.
        /// </summary>
        internal static string EroareLimitaMinimaAviz {
            get {
                return ResourceManager.GetString("EroareLimitaMinimaAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limita minima la chitanta e mai mare decat limita maxima!.
        /// </summary>
        internal static string EroareLimitaMinimaChitanta {
            get {
                return ResourceManager.GetString("EroareLimitaMinimaChitanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limita minima la factura e mai mare decat limita maxima!.
        /// </summary>
        internal static string EroareLimitaMinimaFactura {
            get {
                return ResourceManager.GetString("EroareLimitaMinimaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eroare Necunoscuta.
        /// </summary>
        internal static string EroareNecunoscuta {
            get {
                return ResourceManager.GetString("EroareNecunoscuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eroare la reinitalizare!.
        /// </summary>
        internal static string EroareReinitializare {
            get {
                return ResourceManager.GetString("EroareReinitializare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datele nu s-au salvat!.
        /// </summary>
        internal static string EroareSalvareDate {
            get {
                return ResourceManager.GetString("EroareSalvareDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targetul nu poate fi salvat!.
        /// </summary>
        internal static string EroareSalvareTarget {
            get {
                return ResourceManager.GetString("EroareSalvareTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seria chitantei nu este buna!.
        /// </summary>
        internal static string EroareSerieChitanta {
            get {
                return ResourceManager.GetString("EroareSerieChitanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seria facturii nu este buna!.
        /// </summary>
        internal static string EroareSerieFactura {
            get {
                return ResourceManager.GetString("EroareSerieFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge un aviz!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergeAviz {
            get {
                return ResourceManager.GetString("EroareStergeAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o pozitie din stoc!.
        /// </summary>
        internal static string EroareStergePozitie {
            get {
                return ResourceManager.GetString("EroareStergePozitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o campanie!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereCampanie {
            get {
                return ResourceManager.GetString("EroareStergereCampanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o categorie de client!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereCategorieClient {
            get {
                return ResourceManager.GetString("EroareStergereCategorieClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge un client!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereClient {
            get {
                return ResourceManager.GetString("EroareStergereClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o comanda!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereComanda {
            get {
                return ResourceManager.GetString("EroareStergereComanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divizia nu poate fi stearsa!.
        /// </summary>
        internal static string EroareStergereDivizie {
            get {
                return ResourceManager.GetString("EroareStergereDivizie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti voie sa stergeti un document de plata!.
        /// </summary>
        internal static string EroareStergereDocumentPlata {
            get {
                return ResourceManager.GetString("EroareStergereDocumentPlata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o gestiune!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereGestiuni {
            get {
                return ResourceManager.GetString("EroareStergereGestiuni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o grupa!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereGrupa {
            get {
                return ResourceManager.GetString("EroareStergereGrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o grupa de discounturi!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereGrupaDiscount {
            get {
                return ResourceManager.GetString("EroareStergereGrupaDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o grupa de pret!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereGrupaPret {
            get {
                return ResourceManager.GetString("EroareStergereGrupaPret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge un motiv!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereMotiv {
            get {
                return ResourceManager.GetString("EroareStergereMotiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o oferta!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereOferta {
            get {
                return ResourceManager.GetString("EroareStergereOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti sterge pozitia, avizul a este anulat!.
        /// </summary>
        internal static string EroareStergerePozitieAvizAnulat {
            get {
                return ResourceManager.GetString("EroareStergerePozitieAvizAnulat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti sterge pozitia, avizul a fost preluat pe telefon!.
        /// </summary>
        internal static string EroareStergerePozitieAvizPreluat {
            get {
                return ResourceManager.GetString("EroareStergerePozitieAvizPreluat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteti sterge pozitia, avizul este validat!.
        /// </summary>
        internal static string EroareStergerePozitieAvizValidat {
            get {
                return ResourceManager.GetString("EroareStergerePozitieAvizValidat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge un producator!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereProducator {
            get {
                return ResourceManager.GetString("EroareStergereProducator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge un produs!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereProdus {
            get {
                return ResourceManager.GetString("EroareStergereProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o ruta!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereRuta {
            get {
                return ResourceManager.GetString("EroareStergereRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o serie!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereSerie {
            get {
                return ResourceManager.GetString("EroareStergereSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o subgrupa!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereSubgrupa {
            get {
                return ResourceManager.GetString("EroareStergereSubgrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o sub-subgrupa!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereSubsubgrupa {
            get {
                return ResourceManager.GetString("EroareStergereSubsubgrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge un telefon!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereTelefon {
            get {
                return ResourceManager.GetString("EroareStergereTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o unitate de masura!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereUM {
            get {
                return ResourceManager.GetString("EroareStergereUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge o zona!!! Eventual se anuleaza!.
        /// </summary>
        internal static string EroareStergereZona {
            get {
                return ResourceManager.GetString("EroareStergereZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate sterge un utilizator, eventual anulati-l!.
        /// </summary>
        internal static string EroareStergeUtilizator {
            get {
                return ResourceManager.GetString("EroareStergeUtilizator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} agenti in subordine, nu puteti sterge accesul pe zona {1}!.
        /// </summary>
        internal static string EroareStergeUtilizatorZone {
            get {
                return ResourceManager.GetString("EroareStergeUtilizatorZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avizul nu se poate valida fara pozitii!.
        /// </summary>
        internal static string EroareValidareAviz {
            get {
                return ResourceManager.GetString("EroareValidareAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma blocata! Contactati firma QUALTEH!.
        /// </summary>
        internal static string FirmaBlocata {
            get {
                return ResourceManager.GetString("FirmaBlocata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai este o firma cu aceeasi denumire!.
        /// </summary>
        internal static string FirmaDublata {
            get {
                return ResourceManager.GetString("FirmaDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o gestiune cu aceeasi denumire!.
        /// </summary>
        internal static string GestiuneDublata {
            get {
                return ResourceManager.GetString("GestiuneDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiunea {0} nu exista in sistem!.
        /// </summary>
        internal static string GestiuneInexistenta {
            get {
                return ResourceManager.GetString("GestiuneInexistenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o grupa de discounturi produs cu aceeasi denumire!.
        /// </summary>
        internal static string GrupaDiscountProdusDublat {
            get {
                return ResourceManager.GetString("GrupaDiscountProdusDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o grupa de discounturi cu aceeasi denumire!.
        /// </summary>
        internal static string GrupaDiscounturiClientiDublat {
            get {
                return ResourceManager.GetString("GrupaDiscounturiClientiDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti o grupa cu aceeasi denumire!.
        /// </summary>
        internal static string GrupaDublata {
            get {
                return ResourceManager.GetString("GrupaDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista o grupa de preturi cu aceeasi denumire!.
        /// </summary>
        internal static string GrupaPreturiClientDublata {
            get {
                return ResourceManager.GetString("GrupaPreturiClientDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail incorect, sau casuta de mail indisponibila!.
        /// </summary>
        internal static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailul este invalid pe oferta {0}: email= {1}.
        /// </summary>
        internal static string InvalidEmailOferta {
            get {
                return ResourceManager.GetString("InvalidEmailOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailul este invalid pe oferta {0}: email persoana contact= {1}.
        /// </summary>
        internal static string InvalidEmailPersoana {
            get {
                return ResourceManager.GetString("InvalidEmailPersoana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid!.
        /// </summary>
        internal static string InvalidEmailRegister {
            get {
                return ResourceManager.GetString("InvalidEmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailurile sunt invalide pe oferta {0}: email= {1}; email persoana contact= {2}.
        /// </summary>
        internal static string InvalidEmailuriOferta {
            get {
                return ResourceManager.GetString("InvalidEmailuriOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti agenti setati!.
        /// </summary>
        internal static string LipsaAgent {
            get {
                return ResourceManager.GetString("LipsaAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un agent!.
        /// </summary>
        internal static string LipsaAgent1 {
            get {
                return ResourceManager.GetString("LipsaAgent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu sunteti autentificat!.
        /// </summary>
        internal static string LipsaAutentificare {
            get {
                return ResourceManager.GetString("LipsaAutentificare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie sa va autentificati!.
        /// </summary>
        internal static string LipsaAutentificare1 {
            get {
                return ResourceManager.GetString("LipsaAutentificare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un aviz!.
        /// </summary>
        internal static string LipsaAviz {
            get {
                return ResourceManager.GetString("LipsaAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un Buletin de Identitate sau Carte de Identitate!.
        /// </summary>
        internal static string LipsaBI {
            get {
                return ResourceManager.GetString("LipsaBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o cantitate!.
        /// </summary>
        internal static string LipsaCantitate {
            get {
                return ResourceManager.GetString("LipsaCantitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o categorie de client!.
        /// </summary>
        internal static string LipsaCategorieClient {
            get {
                return ResourceManager.GetString("LipsaCategorieClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti categorie de clienti!.
        /// </summary>
        internal static string LipsaCategorieClienti {
            get {
                return ResourceManager.GetString("LipsaCategorieClienti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un client pe oferta!.
        /// </summary>
        internal static string LipsaClientOferta {
            get {
                return ResourceManager.GetString("LipsaClientOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un client pe comanda!.
        /// </summary>
        internal static string LipsaClientPeComanda {
            get {
                return ResourceManager.GetString("LipsaClientPeComanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un CNP!.
        /// </summary>
        internal static string LipsaCNP {
            get {
                return ResourceManager.GetString("LipsaCNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu exista clientul cu codul: {0}.
        /// </summary>
        internal static string LipsaCodClient {
            get {
                return ResourceManager.GetString("LipsaCodClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu exista comanda cu Id {0}.
        /// </summary>
        internal static string LipsaComandaID {
            get {
                return ResourceManager.GetString("LipsaComandaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lipsa conexiune baza date!.
        /// </summary>
        internal static string LipsaConexiune {
            get {
                return ResourceManager.GetString("LipsaConexiune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un continut!.
        /// </summary>
        internal static string LipsaContinutMesaj {
            get {
                return ResourceManager.GetString("LipsaContinutMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un CUI la client!.
        /// </summary>
        internal static string LipsaCUI {
            get {
                return ResourceManager.GetString("LipsaCUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la campanie!.
        /// </summary>
        internal static string LipsaDenumireCampanie {
            get {
                return ResourceManager.GetString("LipsaDenumireCampanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la categorie de client!.
        /// </summary>
        internal static string LipsaDenumireCategorieClient {
            get {
                return ResourceManager.GetString("LipsaDenumireCategorieClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la client!.
        /// </summary>
        internal static string LipsaDenumireClient {
            get {
                return ResourceManager.GetString("LipsaDenumireClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la divizie!.
        /// </summary>
        internal static string LipsaDenumireDivizie {
            get {
                return ResourceManager.GetString("LipsaDenumireDivizie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti denumirea firmei!.
        /// </summary>
        internal static string LipsaDenumireFirma {
            get {
                return ResourceManager.GetString("LipsaDenumireFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la gestiune!.
        /// </summary>
        internal static string LipsaDenumireGestiune {
            get {
                return ResourceManager.GetString("LipsaDenumireGestiune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la grupa!.
        /// </summary>
        internal static string LipsaDenumireGrupa {
            get {
                return ResourceManager.GetString("LipsaDenumireGrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la grupa de discounturi!.
        /// </summary>
        internal static string LipsaDenumireGrupaDiscount {
            get {
                return ResourceManager.GetString("LipsaDenumireGrupaDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la grupa de pret!.
        /// </summary>
        internal static string LipsaDenumireGrupaPret {
            get {
                return ResourceManager.GetString("LipsaDenumireGrupaPret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la motiv!.
        /// </summary>
        internal static string LipsaDenumireMotiv {
            get {
                return ResourceManager.GetString("LipsaDenumireMotiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la producator!.
        /// </summary>
        internal static string LipsaDenumireProducator {
            get {
                return ResourceManager.GetString("LipsaDenumireProducator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la produs!.
        /// </summary>
        internal static string LipsaDenumireProdus {
            get {
                return ResourceManager.GetString("LipsaDenumireProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la subgrupa!.
        /// </summary>
        internal static string LipsaDenumireSubgrupa {
            get {
                return ResourceManager.GetString("LipsaDenumireSubgrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la sub-subgrupa!.
        /// </summary>
        internal static string LipsaDenumireSubsubgrupa {
            get {
                return ResourceManager.GetString("LipsaDenumireSubsubgrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la unitate de masura a valabilitatii!.
        /// </summary>
        internal static string LipsaDenumireUMValabilitate {
            get {
                return ResourceManager.GetString("LipsaDenumireUMValabilitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la zona!.
        /// </summary>
        internal static string LipsaDenumireZona {
            get {
                return ResourceManager.GetString("LipsaDenumireZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o denumire la unitate de masura!.
        /// </summary>
        internal static string LipsaDenumirUM {
            get {
                return ResourceManager.GetString("LipsaDenumirUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un destinatar!.
        /// </summary>
        internal static string LipsaDestinatarMesaj {
            get {
                return ResourceManager.GetString("LipsaDestinatarMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu exista document plata cu id {0}.
        /// </summary>
        internal static string LipsaDocumentPlataID {
            get {
                return ResourceManager.GetString("LipsaDocumentPlataID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un email!.
        /// </summary>
        internal static string LipsaEmail {
            get {
                return ResourceManager.GetString("LipsaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un expeditor!.
        /// </summary>
        internal static string LipsaExpeditor {
            get {
                return ResourceManager.GetString("LipsaExpeditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu este setata firma!!!.
        /// </summary>
        internal static string LipsaFirma {
            get {
                return ResourceManager.GetString("LipsaFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o gestiune!.
        /// </summary>
        internal static string LipsaGestiune {
            get {
                return ResourceManager.GetString("LipsaGestiune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un gramaj si o unitate de masura pentru gramaj sau stergetile pe amandoua!.
        /// </summary>
        internal static string LipsaGramaj {
            get {
                return ResourceManager.GetString("LipsaGramaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o grupa de discounturi client!.
        /// </summary>
        internal static string LipsaGrupaDiscounturi {
            get {
                return ResourceManager.GetString("LipsaGrupaDiscounturi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o grupa pentru produs!.
        /// </summary>
        internal static string LipsaGrupaProdus {
            get {
                return ResourceManager.GetString("LipsaGrupaProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti grupe de produse!.
        /// </summary>
        internal static string LipsaGrupeProduse {
            get {
                return ResourceManager.GetString("LipsaGrupeProduse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un IMEI!.
        /// </summary>
        internal static string LipsaIMEI {
            get {
                return ResourceManager.GetString("LipsaIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o lista de pret!.
        /// </summary>
        internal static string LipsaListaPret {
            get {
                return ResourceManager.GetString("LipsaListaPret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ati specificat numele membrului testat.
        /// </summary>
        internal static string LipsaMembru {
            get {
                return ResourceManager.GetString("LipsaMembru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membrul specificat ({0}) nu exista!.
        /// </summary>
        internal static string LipsaMembru1 {
            get {
                return ResourceManager.GetString("LipsaMembru1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un numar de telefon!.
        /// </summary>
        internal static string LipsaNrTelefon {
            get {
                return ResourceManager.GetString("LipsaNrTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un numar la aviz!.
        /// </summary>
        internal static string LipsaNumarAviz {
            get {
                return ResourceManager.GetString("LipsaNumarAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un nume!.
        /// </summary>
        internal static string LipsaNume {
            get {
                return ResourceManager.GetString("LipsaNume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ati specificat numele parametrului.
        /// </summary>
        internal static string LipsaNumeParametru {
            get {
                return ResourceManager.GetString("LipsaNumeParametru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un nume de ruta!.
        /// </summary>
        internal static string LipsaNumeRuta {
            get {
                return ResourceManager.GetString("LipsaNumeRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un nume de utilizator!.
        /// </summary>
        internal static string LipsaNumeUtilizator {
            get {
                return ResourceManager.GetString("LipsaNumeUtilizator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o parola!.
        /// </summary>
        internal static string LipsaParola {
            get {
                return ResourceManager.GetString("LipsaParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un prenume!.
        /// </summary>
        internal static string LipsaPrenume {
            get {
                return ResourceManager.GetString("LipsaPrenume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o lista de pret pe client!.
        /// </summary>
        internal static string LipsaPretClient {
            get {
                return ResourceManager.GetString("LipsaPretClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu exista produsul cu codul {0}.
        /// </summary>
        internal static string LipsaProdus {
            get {
                return ResourceManager.GetString("LipsaProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un produs!.
        /// </summary>
        internal static string LipsaProdus1 {
            get {
                return ResourceManager.GetString("LipsaProdus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti produse pe comanda!.
        /// </summary>
        internal static string LipsaProduseComanda {
            get {
                return ResourceManager.GetString("LipsaProduseComanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu aveti produse pe oferta!.
        /// </summary>
        internal static string LipsaProduseOferta {
            get {
                return ResourceManager.GetString("LipsaProduseOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produsul nu are ID sau cod extern/simbol!.
        /// </summary>
        internal static string LipsaProdusID {
            get {
                return ResourceManager.GetString("LipsaProdusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o serie la aviz!.
        /// </summary>
        internal static string LipsaSerieAviz {
            get {
                return ResourceManager.GetString("LipsaSerieAviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un subiect!.
        /// </summary>
        internal static string LipsaSubiectMesaj {
            get {
                return ResourceManager.GetString("LipsaSubiectMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti o suma!.
        /// </summary>
        internal static string LipsaSuma {
            get {
                return ResourceManager.GetString("LipsaSuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti un numar de telefon!.
        /// </summary>
        internal static string LipsaTelefon {
            get {
                return ResourceManager.GetString("LipsaTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un telefon!.
        /// </summary>
        internal static string LipsaTelefon1 {
            get {
                return ResourceManager.GetString("LipsaTelefon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentul {0} nu are telefon setat!.
        /// </summary>
        internal static string LipsaTelefonAgent {
            get {
                return ResourceManager.GetString("LipsaTelefonAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o unitate de masura!.
        /// </summary>
        internal static string LipsaUM {
            get {
                return ResourceManager.GetString("LipsaUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o unitate de masura pentru produs!.
        /// </summary>
        internal static string LipsaUMProdus {
            get {
                return ResourceManager.GetString("LipsaUMProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un utilizator!.
        /// </summary>
        internal static string LipsaUtilizator {
            get {
                return ResourceManager.GetString("LipsaUtilizator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un utilizator pe oferta!.
        /// </summary>
        internal static string LipsaUtilizatorOferta {
            get {
                return ResourceManager.GetString("LipsaUtilizatorOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati un utilizator pe comanda!.
        /// </summary>
        internal static string LipsaUtilizatorPeComanda {
            get {
                return ResourceManager.GetString("LipsaUtilizatorPeComanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o valabilitate si o unitate de masura pentru valabilitate sau stergetile pe amandoua!.
        /// </summary>
        internal static string LipsaValabilitate {
            get {
                return ResourceManager.GetString("LipsaValabilitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ati specificat valoarea parametrului.
        /// </summary>
        internal static string LipsaValoareParametru {
            get {
                return ResourceManager.GetString("LipsaValoareParametru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o zona!.
        /// </summary>
        internal static string LipsaZona {
            get {
                return ResourceManager.GetString("LipsaZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectati o zona pe client!.
        /// </summary>
        internal static string LipsaZonaClient {
            get {
                return ResourceManager.GetString("LipsaZonaClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un motiv cu aceeasi denumire!.
        /// </summary>
        internal static string MotivDublat {
            get {
                return ResourceManager.GetString("MotivDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} clienti pe aceasta zona! Va rugam realocati clientii pe alta zona inainte de anulare..
        /// </summary>
        internal static string NrClientiZona {
            get {
                return ResourceManager.GetString("NrClientiZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta unitate de masura la gramaj! Va rugam realocati produsele pe alta unitate de masura inainte de anulare.
        /// </summary>
        internal static string NrProduseGramaj {
            get {
                return ResourceManager.GetString("NrProduseGramaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta subgrupa! Va rugam realocati produsele pe alta subgrupa inainte de anulare.
        /// </summary>
        internal static string NrProduseSubgrupa {
            get {
                return ResourceManager.GetString("NrProduseSubgrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta subsubgrupa! Va rugam realocati produsele pe alta subsubgrupa inainte de anulare.
        /// </summary>
        internal static string NrProduseSubsubgrupa {
            get {
                return ResourceManager.GetString("NrProduseSubsubgrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta unitate de masura! Va rugam realocati produsele pe alta unitate de masura inainte de anulare.
        /// </summary>
        internal static string NrProduseUM {
            get {
                return ResourceManager.GetString("NrProduseUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aveti {0} produse pe aceasta unitate de masura a valabilitatii! Va rugam realocati produsele pe alta unitate de masura a valabilitatii inainte de anulare.
        /// </summary>
        internal static string NrProduseUMValabilitate {
            get {
                return ResourceManager.GetString("NrProduseUMValabilitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul chitantei este mai mare decat limita maxima!.
        /// </summary>
        internal static string NumarChitantaMaiMareLimita {
            get {
                return ResourceManager.GetString("NumarChitantaMaiMareLimita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul chitantei mai mic sau egal cu numarul curent inregistrat pentru aceasta serie!.
        /// </summary>
        internal static string NumarChitantaMaiMicCurent {
            get {
                return ResourceManager.GetString("NumarChitantaMaiMicCurent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul chitantei este mai mic decat limita minima!.
        /// </summary>
        internal static string NumarChitantaMaiMicLimita {
            get {
                return ResourceManager.GetString("NumarChitantaMaiMicLimita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul facturii este mai mare decat limita maxima!.
        /// </summary>
        internal static string NumarFacturaMaiMareLimita {
            get {
                return ResourceManager.GetString("NumarFacturaMaiMareLimita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul facturii mai mic sau egal cu numarul curent inregistrat pentru aceasta serie!.
        /// </summary>
        internal static string NumarFacturaMaiMicCurent {
            get {
                return ResourceManager.GetString("NumarFacturaMaiMicCurent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul facturii este mai mic decat limita minima!.
        /// </summary>
        internal static string NumarFacturaMaiMicLimita {
            get {
                return ResourceManager.GetString("NumarFacturaMaiMicLimita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        internal static string Oferta {
            get {
                return ResourceManager.GetString("Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Buna ziua,&lt;/b&gt;&lt;BR&gt;
        ///&lt;BR&gt;
        ///&lt;b&gt;Conform discutiei, atasat va trimit oferta &lt;/b&gt;&lt;BR&gt;
        ///&lt;BR&gt;
        ///&lt;BR&gt;
        ///&lt;BR&gt;
        ///Al dumneavoastra,
        ///&lt;BR&gt;
        ///{0}&lt;BR&gt;
        ///{1}&lt;BR&gt;
        ///{2}&lt;BR&gt;
        ///{3}&lt;BR&gt;.
        /// </summary>
        internal static string OfertaBodyMail {
            get {
                return ResourceManager.GetString("OfertaBodyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista un pret identic!.
        /// </summary>
        internal static string PretDublat {
            get {
                return ResourceManager.GetString("PretDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista un producator cu aceeasi denumire!.
        /// </summary>
        internal static string ProducatorDublat {
            get {
                return ResourceManager.GetString("ProducatorDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista un produs cu acelasi cod extern!.
        /// </summary>
        internal static string ProdusCodExternDublat {
            get {
                return ResourceManager.GetString("ProdusCodExternDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista un produs cu acelasi cod intern!.
        /// </summary>
        internal static string ProdusCodIntenDublat {
            get {
                return ResourceManager.GetString("ProdusCodIntenDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista un produs cu aceeasi denumire!.
        /// </summary>
        internal static string ProdusDublat {
            get {
                return ResourceManager.GetString("ProdusDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatie interzisa, produsul nu este pe gestiune!.
        /// </summary>
        internal static string ProdusLipsaGestiune {
            get {
                return ResourceManager.GetString("ProdusLipsaGestiune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista o ruta cu aceeasi denumire!.
        /// </summary>
        internal static string RutaDublata {
            get {
                return ResourceManager.GetString("RutaDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bine ati venit!.
        /// </summary>
        internal static string SendEmailRegister {
            get {
                return ResourceManager.GetString("SendEmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Va multumim!.
        /// </summary>
        internal static string SendEmailSubject {
            get {
                return ResourceManager.GetString("SendEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti seria de aviz {0} cu aceleasi limite!.
        /// </summary>
        internal static string SerieAvizDublat {
            get {
                return ResourceManager.GetString("SerieAvizDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti seria de chitanta {0} cu aceleasi limite!.
        /// </summary>
        internal static string SerieChitantaDublat {
            get {
                return ResourceManager.GetString("SerieChitantaDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti seria de factura {0} cu aceleasi limite!.
        /// </summary>
        internal static string SerieFacturaDublat {
            get {
                return ResourceManager.GetString("SerieFacturaDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista stocul!.
        /// </summary>
        internal static string StocDublat {
            get {
                return ResourceManager.GetString("StocDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista o subgrupa cu aceeasi denumire.
        /// </summary>
        internal static string SubgrupaDublata {
            get {
                return ResourceManager.GetString("SubgrupaDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista o subsubgrupa cu aceeasi denumire!.
        /// </summary>
        internal static string SubsubgrupaDublata {
            get {
                return ResourceManager.GetString("SubsubgrupaDublata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti agentul {0} pe telefonul {1}!.
        /// </summary>
        internal static string TelefonAgentiDublat {
            get {
                return ResourceManager.GetString("TelefonAgentiDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon blocat. Contactati firma QUALTEH!.
        /// </summary>
        internal static string TelefonBlocat {
            get {
                return ResourceManager.GetString("TelefonBlocat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonul a fost blocat de la sediu!.
        /// </summary>
        internal static string TelefonBlocatSediu {
            get {
                return ResourceManager.GetString("TelefonBlocatSediu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista acelasi telefon!.
        /// </summary>
        internal static string TelefonDublat {
            get {
                return ResourceManager.GetString("TelefonDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon inregistrat pe alta firma. Contactati firma QUALTEH!.
        /// </summary>
        internal static string TelefonInregistrat {
            get {
                return ResourceManager.GetString("TelefonInregistrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport vizite si sold client
        ///
        ///--------------------------------------------------------
        ///
        ///{0}
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///{3}
        ///
        ///--------------------------------------------------------
        ///
        ///sold punct de lucru: {4}
        ///sold total: {5}
        ///
        ///--------------------------------------------------------
        ///
        ///{6}
        ///
        ///--------------------------------------------------------
        ///
        ///Ultimele 10 vizite:
        ///{7}
        ///--------------------------------------------------------.
        /// </summary>
        internal static string TemplateVerificareClient {
            get {
                return ResourceManager.GetString("TemplateVerificareClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda.
        /// </summary>
        internal static string TemplateVerificareClientComanda {
            get {
                return ResourceManager.GetString("TemplateVerificareClientComanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}
        ///{2}
        ///{3} {4} {5}  {6} {7} {8}.
        /// </summary>
        internal static string TemplateVerificareClientDetaliu {
            get {
                return ResourceManager.GetString("TemplateVerificareClientDetaliu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incasare.
        /// </summary>
        internal static string TemplateVerificareClientIncasare {
            get {
                return ResourceManager.GetString("TemplateVerificareClientIncasare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toti agentii.
        /// </summary>
        internal static string TotiAgentii {
            get {
                return ResourceManager.GetString("TotiAgentii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista o UM cu aceeasi denumire!.
        /// </summary>
        internal static string UMDublat {
            get {
                return ResourceManager.GetString("UMDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista o UM valabilitate cu aceeasi denumire!.
        /// </summary>
        internal static string UMValabilitateDublat {
            get {
                return ResourceManager.GetString("UMValabilitateDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul este anulat!.
        /// </summary>
        internal static string UtilizatorAnulat {
            get {
                return ResourceManager.GetString("UtilizatorAnulat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti un utilizator cu aceleasi date de autentificare: {0}!.
        /// </summary>
        internal static string UtilizatorDublat {
            get {
                return ResourceManager.GetString("UtilizatorDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista un angajat cu acelasi nume, prenume si CNP!.
        /// </summary>
        internal static string UtilizatorDublat1 {
            get {
                return ResourceManager.GetString("UtilizatorDublat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator inexistent! {0}.
        /// </summary>
        internal static string UtilizatorInexistent {
            get {
                return ResourceManager.GetString("UtilizatorInexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai aveti zona {0} definita pe managerul {1}!.
        /// </summary>
        internal static string UtilizatorZonaDublat {
            get {
                return ResourceManager.GetString("UtilizatorZonaDublat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai exista o zona cu aceeasi denumire!.
        /// </summary>
        internal static string ZonaDublata {
            get {
                return ResourceManager.GetString("ZonaDublata", resourceCulture);
            }
        }
    }
}
